### ISSUE TITLE
Error on Import

### ISSUE THREAD

**Issue by bmotley** [Church-17/autocombobox#1]
Importing the module (using juypter notebook), I receive this error:

TypeError                                 Traceback (most recent call last)
Input In [43], in <cell line: 8>()
      6 import os
      7 import win32com.client
----> 8 import autocombobox

File ~\Anaconda3\lib\site-packages\autocombobox\__init__.py:7, in <module>
      3 from tkinter.ttk import Combobox, Scrollbar
      5 __version__ = "1.0.1"
----> 7 class AutoCombobox(Combobox):
      8     """Autocomplete Combobox"""
     10     def __init__(self, *args, **kwargs):

File ~\Anaconda3\lib\site-packages\autocombobox\__init__.py:81, in AutoCombobox()
     78     self.change_highlight(-1)
     79     self._is_posted = False
---> 81 def update_values(self, text: str | None = None):
     82     """Update listbox values to show coherent options"""
     84     # Check params

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by Church-17** [comment]
Which Python version are you using?

**Comment by Church-17** [comment]
`text: str | None` indicates that the variable `text` can be a string or None, and this notation is been added only in Python 3.10. I apologise if I didn't indicate more explicitly the minimum version required by this package, I'll write it in the docs as soon as possible, I'm sorry for this inconvenience
